'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class Negocios2015Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Negocios2015Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property clientes() As DbSet(Of clientes)
    Public Overridable Property paises() As DbSet(Of paises)

    Public Overridable Function usp_ClienteListado_EDM() As ObjectResult(Of usp_ClienteListado_EDM_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_ClienteListado_EDM_Result)("usp_ClienteListado_EDM")
    End Function

    Public Overridable Function usp_PaisListar_EDM() As ObjectResult(Of usp_PaisListar_EDM_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_PaisListar_EDM_Result)("usp_PaisListar_EDM")
    End Function

End Class
